# Generated by Django 6.0.2 on 2026-03-04 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0004_alter_product_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0, verbose_name='Сумма')),
                ('product', models.ManyToManyField(related_name='product_carts', to='products.product', verbose_name='Продукт')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_carts', to='accounts.account', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
    ]
