# Generated by Django 6.0.2 on 2026-02-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('currency', models.CharField(choices=[('dollar', 'Dollar'), ('som', 'Som'), ('euro', 'Euro')], default='som', max_length=20, verbose_name='Валюта')),
                ('image', models.ImageField(blank=True, upload_to='product_images', verbose_name='Картинка')),
                ('color', models.CharField(choices=[('dollar', 'Dollar'), ('som', 'Som'), ('euro', 'Euro')], max_length=20, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
