# Generated by Django 6.0.2 on 2026-02-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('yellow', 'Yellow'), ('green', 'Green')], max_length=20, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('dollar', 'Dollar'), ('som', 'Som'), ('euro', 'Euro')], default='som', max_length=20, verbose_name='Валюта'),
        ),
    ]
