# Generated by Django 6.0.2 on 2026-03-10 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0005_alter_product_currency_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='categories.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('dollar', 'Dollar'), ('som', 'Som'), ('euro', 'Euro')], default='som', max_length=20, verbose_name='Валюта'),
        ),
    ]
