# Generated by Django 6.0.2 on 2026-03-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('dollar', 'Dollar'), ('som', 'Som'), ('euro', 'Euro')], default='som', max_length=20, verbose_name='Валюта'),
        ),
    ]
